export const questionData = [
    { value: "问题1" },
    { value: "问题2" },
    { value: "问题3" },
    { value: "问题4" },
    { value: "问题5" },
    { value: "问题6" },
    { value: "问题7" },
    { value: "问题8" },
    { value: "问题9" },
    { value: "问题10" },
    { value: "问题11" },
    { value: "问题12" },
    { value: "问题13" },
    { value: "问题14" },
    { value: "问题15" },
    { value: "问题16" },
    { value: "问题17" },
    { value: "问题18" },
    { value: "问题19" },
    { value: "问题20" },
    { value: "问题21" },
    { value: "问题22" },
];